Support asa ID in `deployer.OptIn*`
scale-it/algo-builder pull request #295
Opened 2021-04-26 18:30 UTC by man-of-code

2021-04-27 08:50 UTC, amityadav0 commented
Please add a test, showing we can retreive asset info from checkpoint using asa id. You can refer to some Tests in checkpoints test section.

2021-04-27 11:57 UTC, man-of-code commented
> Please add a test, showing we can retreive asset info from checkpoint using asa id. You can refer to some Tests in checkpoints test section.

@amityadav0  My understanding is that this task was to provide support for ASA not deployed by `deployer` (not existing in checkpoints). @ratik21 Has added a function in this [PR](https://github.com/scale-it/algo-builder/pull/293) with the same functionality you are talking about.

2021-04-27 12:05 UTC, amityadav0 commented
@man-of-code right, we may have overestimated this task.

2021-05-03 08:48 UTC, amityadav0 requested changes
I don't think we support this in `executeTransaction`. Please add these checks there.

2021-05-03 08:48 UTC, amityadav0 commented on packages/algob/src/internal/deployer.ts
> +      console.log(error);
let's change this log here, maybe to asset not found in checkpoints proceeding to process it as asset ID

2021-05-03 08:48 UTC, amityadav0 commented on packages/algob/src/internal/deployer.ts
> +        throw Error("Please provide a valid Number to be used as ASA ID");
This error should show both cases - 1. asset not in checkpoints also asset is not valid ASA ID

2021-05-03 08:48 UTC, amityadav0 commented on packages/algob/src/internal/deployer.ts
> +   * @param asa ASA (name/ID)
Please add here ID can be used for ASA not existing in checkpoints

2021-05-03 08:48 UTC, amityadav0 commented on packages/algob/src/internal/deployer.ts
> +      console.log(error);
Please update this function as per suggestions in Lsig function

2021-05-04 12:20 UTC, man-of-code commented
> I don't think we support this in `executeTransaction`. Please add these checks there.

@amityadav0 while executing any asset related transaction using `executeTransaction` we are already sending AssetID.

2021-05-12 08:49 UTC, amityadav0 approved these changes

2021-05-12 15:40 UTC, merged